## Travis CI Integration
language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - mozroots --import --sync
  - mono --runtime=v4 nuget.exe update -self
  - mono --runtime=v4 nuget.exe restore blazey.features.sln
  - xbuild blazey.features.sln
  - nunit-console features.specs/bin/Debug/features.specs.dll